### ISSUE TITLE
How to retain coenzymes or non-canonical residues in proteins

### ISSUE THREAD

**Issue by 12228086** [Hoecker-Lab/pocketoptimizer#10]
Dear Jakob,

I want to use the pocket-optimizer package to optimise my transaminases. I would like to ask what should I do with my coenzyme PMP, I think deleting the PMP directly should have a bad effect on the subsequent energy calculations. I would like to know how I can get the PMP to generate parm files with the proteins.

Thank you again for your help and insight.

All the best,
Teng

**Comment by jnoske** [comment]
Dear Teng,

Thanks for reaching out. Unfortunately I dont think it is possible without extensive modifications of the code to retain cofactors or non-canonical amino acids as these have to be parameterized and rotamers or conformations for these residues need to be generated. Deleting/Ignoring the cofactor is unfortunately the only possibility for you and this causes indeed some inconsistencies with the energy function.

**Comment by 12228086** [comment]
Thank you for your prompt reply
I have two more questions:
1 Is it feasible to use dual ligands for design?
2 If I wish to use the resp charge of my own fitted ligand, how should I make the substitution？Is it possible to directly replace the parm parameter file of the complex in native_complex？

**Comment by jnoske** [comment]
1 No I dont think this is feasible as many of the subsequent steps would fail
2 Yes in theory it should be possible to use resp charges by modifying lines 180 and 196 in "pocketoptimizer/preparation/structure_building.py" ('-c', 'gas' -> '-c', 'resp'). But this has not been tested and there is no guarantee for this to work properly. Otherwise you can try to modify the charges yourself in YOUR_DESIGN/ligand/amber_ff14SB/ligand.mol2 file.

**Comment by 12228086** [comment]
Thanks for your answer
