### ISSUE TITLE
Ligand parametrization

### ISSUE THREAD

**Issue by LDornfeld** [Hoecker-Lab/pocketoptimizer#3]
Dear Jakob,

When using the pocket-optimizer package, I was wondering about the ligand parametrization process. Specifically, I noticed that the package first parametrises the ligand using a force field such as AMBER (GAFF) or CHARMM, but then one (can) use a different scoring function such as the one of Autodock Vina to calculate the binding energy.

I would like to know why the package first parametrises the ligand with a force field before using a different scoring function for binding-energy calculation. What is the reasoning behind this approach?

Thank you again for your help and insight.

All the best, 
Lars

**Comment by jnoske** [comment]
Dear Lars

You are right, the ligand parameters are not required in this case for the energy calculations using the Autodock Vina scoring function. However, since a minimization step of the protein scaffold is initially performed with the ligand inside the binding pocket, parameters are needed for this step.

Best,
Jakob
